/** Guarda la el nombre de la propiedad 'name' de una ruta de vue para redirigir hacia esa ruta */
export enum RutasNomina {
  Login = "nomina_login",
  Home = "nomina_home",
  Auditoria = "nomina_auditoria",
  CrearAdmin = "nomina_crear_admin",
  VerAdmins = "nomina_ver_admins",
  DetalleAdmin = "nomina_info_admin",
  AsisMultiples = "nomina_asistencias_multiples",
  RegistroEmpleado = "nomina_registro_empleado",
  HistorialEmpleados = "nomina_empleado_historial",
  PuestosEmpleados = "nomina_empleado_puestos",
  ListaEmpleados = "nomina_empleado_listar",
  PerfilEmpleado = "nomina_empleado_base",
  InfoEmpleado = "nomina_empleado_info",
  AsistenciasEmpleado = "nomina_empleado_asistencias",
  DescuentosEmpleado = "nomina_empleado_descuentos",
  BonosEmpleado = "nomina_empleado_bonos",
  SueldosEmpleado = "nomina_empleado_sueldos",
  VacacionesEmpleado = "nomina_empleado_vacaciones",
  SucursalNomina = "nomina_sucursal_nomina",
  SucursalReglas = "nomina_sucursal_reglas",
  SucursalDatos = "nomina_sucursal_datos",
  SucursalGastos = "nomina_sucursal_gastos",
}
